### PR TITLE
fix(rest): return 400 when body gets bad content

### PR DESCRIPTION
**Pull request by ziadsawalha**
We were getting 500’s instead.

### CODE REVIEW

**Comment by samstav** [comment]
@ziadsawalha did you check out this issue? https://github.com/checkmate/simpl/issues/88

**Comment by ziadsawalha** [comment]
@samstav - good point. This PR tackles the json piece as suggested in the discussion on #88, am I right? If so, it can be merged separately?

I can tackle #88 in a follow up PR (today, hopefully). Works?

**Comment by samstav** [comment]
@ziadsawalha Ok cool. :hammer:

**Comment by ziadsawalha** [comment]
Thanks!

**Pull request merged**
